"""The AI tutor (spec §"AI tutor").

Self-hosted and retrieval-grounded. There is no external model call and no
third-party service: the answer is assembled from EngineVerse's own notes,
formulas and topics, and every sentence points back at the entity it came from.

That constraint is deliberate. A general language model asked "explain Bernoulli's
equation" will produce fluent prose whether or not the platform covers it, and a
student cannot tell a grounded explanation from an invented one. This tutor
instead refuses when the platform has nothing to say, which is the only answer a
study tool should give.

Two consequences worth stating plainly:

- The output is a summary of platform content, not original teaching. Where the
  notes are thin the answer is thin.
- Anything this produces is labelled as AI-generated in the UI and carries the
  source list, because a reader is entitled to check it.
"""
from __future__ import annotations

import json
import re
from typing import Any

from . import db, search
from .security.sanitize import strip_html

# Longest passage taken from any single note section. Long enough to carry a real
# explanation, short enough that the answer stays a summary rather than a copy.
MAX_SECTION_CHARS = 600

# How many source entities are cited. Beyond about five a student stops reading.
MAX_SOURCES = 5

DISCLOSURE = (
    "Generated by the EngineVerse tutor from this platform's own notes. "
    "It is AI-generated: check the sources below before you rely on it."
)


def _clean(text: str) -> str:
    """Strips markup and collapses whitespace.

    Retrieved note bodies are authored content, so a compromised or careless
    author could store markup that a client renders. The client escapes too,
    but the API should not be handing out markup in the first place: the
    contract here is plain text plus the **bold** and `code` subset the tutor
    itself emits.
    """
    return re.sub(r"\s+", " ", strip_html(text or "")).strip()


# Words that carry no subject matter. Without this, "how do I bake a souffle"
# matches on "how" and "do" and the tutor answers with whatever came back.
STOPWORDS = frozenset("""
a about above after again all am an and any are as at be because been before being below between
both but by can cannot could did do does doing down during each few for from further had has have
having he her here hers him his how i if in into is it its itself just me more most my no nor not
of off on once only or other our out over own same she should so some such than that the their them
then there these they this those through to too under until up very was we were what when where
which while who whom why will with would you your
""".split())


def _content_words(question: str) -> list[str]:
    return [w for w in re.split(r"[^a-z0-9]+", question.lower())
            if len(w) > 2 and w not in STOPWORDS]


def _retrieve(question: str) -> list[dict]:
    """Finds the platform content that can legitimately answer this question.

    Uses the same index the global search does, so the tutor cannot surface
    anything a student could not have found themselves - but then keeps only
    the hits that actually mention what was asked about.

    That second step matters more than it sounds. The search falls back from an
    AND match to an OR match to a LIKE match so that a global search is never
    empty, which is right for a search box and wrong for an assistant: asked
    "how do I bake a souffle", the OR fallback returns CPU scheduling notes,
    and a reader cannot tell that is a miss. Requiring the question's own
    subject words to appear in the hit is what turns "we found something" into
    "we found something about this".
    """
    wanted = _content_words(question)
    found = search.search(question, limit=24)
    out: list[dict] = []
    for hit in found.get("results", []):
        snippet = _clean(hit.get("snippet") or "")
        haystack = f"{hit['title']} {snippet}".lower()
        hits = sum(1 for word in wanted if word in haystack)
        if wanted and hits == 0:
            continue  # matched on a stopword or a stray substring; not an answer
        out.append(
            {
                "type": hit["type"],
                "id": hit["id"],
                "title": hit["title"],
                "url": hit["url"],
                "snippet": snippet,
                "body": "",
                "relevance": hits,
            }
        )
        if len(out) >= 12:
            break
    out.sort(key=lambda item: item["relevance"], reverse=True)
    return out


def _section_body(topic_slug: str, tokens: list[str]) -> str:
    """Pulls the most relevant section from the notes on a topic.

    Notes are indexed by their topic's slug because that is the page a reader
    lands on, so the id arriving here is a slug and not a note id. A topic
    carries one note per quality level; the sections of all of them are pooled
    and the best-matching one is taken, so a beginner question is not answered
    only from the advanced note.
    """
    rows = db.query(
        "SELECT sec.kind, sec.title, sec.body, sec.callout "
        "FROM note_sections sec "
        "JOIN notes n ON n.id = sec.note_id "
        "JOIN topics t ON t.id = n.topic_id "
        "WHERE t.slug = ? AND n.status = 'published' "
        "ORDER BY n.quality_level, sec.order_index",
        topic_slug,
    )
    if not rows:
        return ""

    def score(row: dict) -> int:
        haystack = f"{row['title']} {row['body']}".lower()
        return sum(haystack.count(token) for token in tokens)

    best = max(rows, key=score)
    body = _clean(best["body"])
    if len(body) > MAX_SECTION_CHARS:
        body = body[:MAX_SECTION_CHARS].rsplit(" ", 1)[0] + "…"
    return body


def _formula_lines(ids: list[str]) -> list[tuple[str, str, str]]:
    rows = db.query(
        f"SELECT id, name, latex, meaning, application FROM formulas "
        f"WHERE id IN ({','.join('?' * len(ids))}) LIMIT 4",
        *ids,
    ) if ids else []
    return [(r["name"], r["latex"], _clean(r["meaning"] or r["application"] or "")) for r in rows]


def answer(question: str, user_id: str | None = None) -> dict[str, Any]:
    """Answers a study question from platform content alone.

    Returns ``grounded: False`` and an honest message when the platform has
    nothing relevant, rather than composing something plausible.
    """
    question = _clean(question)
    if len(question) < 4:
        return {
            "answer": "",
            "sources": [],
            "grounded": False,
            "disclosure": DISCLOSURE,
            "message": "Ask a question of at least a few words and I will look it up in the notes.",
        }

    hits = _retrieve(question)
    if not hits:
        suggestion = search.did_you_mean(question)
        message = (
            "I could not find anything in the EngineVerse library about that yet, "
            "so I am not going to guess at an answer."
        )
        if suggestion:
            message += f" Did you mean “{suggestion}”?"
        message += " The library grows as subjects are added; try the subject pages or global search."
        return {"answer": "", "sources": [], "grounded": False,
                "disclosure": DISCLOSURE, "message": message}

    tokens = [t for t in re.split(r"[^a-z0-9]+", question.lower()) if len(t) > 2]

    # Numbered citations, resolved once so the answer and the source list agree.
    sources: list[dict] = []
    cited: dict[str, int] = {}

    def cite(hit: dict) -> str:
        """Numbers a source, or returns an empty tag once the list is full.

        Capping the source list *after* composing the answer would leave the
        prose citing a [6] that the reader cannot look up, which is worse than
        not citing at all. So the cap is applied here, at the moment the
        citation is minted, and an over-budget reference is simply dropped.
        """
        key = f"{hit['type']}:{hit['id']}"
        if key in cited:
            return f"[{cited[key]}]"
        if len(sources) >= MAX_SOURCES:
            return ""
        cited[key] = len(sources) + 1
        sources.append({"n": cited[key], "type": hit["type"],
                        "title": hit["title"], "url": hit["url"]})
        return f"[{cited[key]}]"

    def cite_all(hits: list[dict]) -> list[dict]:
        """Numbers a list of hits that the answer does not itself quote."""
        for hit in hits[:MAX_SOURCES]:
            cite(hit)
        return sources

    note_hits = [h for h in hits if h["type"] == "note"][:3]
    topic_hits = [h for h in hits if h["type"] == "topic"][:2]
    formula_hits = [h for h in hits if h["type"] == "formula"][:2]

    if not (note_hits or formula_hits or topic_hits):
        # Something matched - a problem, a project, a video - but nothing that
        # explains the idea. Point at it instead of padding.
        return {
            "answer": "",
            "sources": cite_all(hits),
            "grounded": False,
            "disclosure": DISCLOSURE,
            "message": (
                "I found related material but no explanatory notes for that yet. "
                "These are the closest matches on the platform."
            ),
        }

    paragraphs: list[str] = []

    for hit in note_hits:
        body = _section_body(hit["id"], tokens)
        if not body:
            continue
        paragraphs.append(f"**{hit['title']}** {cite(hit)}\n\n{body}")

    formulas = _formula_lines([h["id"] for h in formula_hits])
    if formulas:
        lines = []
        for name, latex, meaning in formulas:
            owner = next((h for h in formula_hits if h["title"] == name), None)
            tag = cite(owner) if owner else ""
            lines.append(f"- **{name}** {tag} — `{latex}`" + (f" — {meaning}" if meaning else ""))
        paragraphs.append("**Key formulae**\n\n" + "\n".join(lines))

    for hit in topic_hits:
        paragraphs.append(
            f"See also the topic page for **{hit['title']}** {cite(hit)} for worked examples and practice questions."
        )

    if not paragraphs:
        return {
            "answer": "",
            "sources": cite_all(hits),
            "grounded": False,
            "disclosure": DISCLOSURE,
            "message": "The matching notes have no published sections yet, so there is nothing to summarise.",
        }

    text = re.sub(r"[ \t]{2,}", " ", "\n\n".join(paragraphs))
    return {
        "answer": text,
        "sources": sources,
        "grounded": True,
        "disclosure": DISCLOSURE,
        "message": "",
    }
