"""Catalogue seed: universities, colleges, semesters, subjects, curricula."""

UNIVERSITIES = [
    ("generic", "Autonomous / Generic Curriculum", "generic", "India", "Pan-India"),
    ("VTU", "Visvesvaraya Technological University", "VTU", "India", "Karnataka"),
    ("MU", "University of Mumbai", "MU", "India", "Maharashtra"),
    ("AKTU", "Dr. A.P.J. Abdul Kalam Technical University", "AKTU", "India", "Uttar Pradesh"),
    ("ANNA", "Anna University", "ANNA", "India", "Tamil Nadu"),
    ("JNTUH", "Jawaharlal Nehru Technological University Hyderabad", "JNTUH", "India", "Telangana"),
    ("DU", "University of Delhi (Engineering)", "DU", "India", "Delhi"),
    ("IIT", "IIT Common Curriculum", "IIT", "India", "Pan-India"),
    ("MITOCW", "MIT OpenCourseWare Alignment", "MITOCW", "United States", "Massachusetts"),
    ("NPTEL", "NPTEL / AICTE Model Curriculum", "NPTEL", "India", "Pan-India"),
]

COLLEGES = [
    ("VTU", "RV College of Engineering", "Bengaluru"),
    ("VTU", "BMS College of Engineering", "Bengaluru"),
    ("VTU", "National Institute of Engineering Mysuru", "Mysuru"),
    ("MU", "VJTI Mumbai", "Mumbai"),
    ("MU", "DJ Sanghvi College of Engineering", "Mumbai"),
    ("AKTU", "IET Lucknow", "Lucknow"),
    ("ANNA", "CEG Guindy", "Chennai"),
    ("JNTUH", "JNTUH College of Engineering", "Hyderabad"),
    ("DU", "Delhi Technological University", "Delhi"),
    ("IIT", "IIT Bombay", "Mumbai"),
    ("IIT", "IIT Delhi", "Delhi"),
    ("IIT", "IIT Madras", "Chennai"),
    ("generic", "Self-taught / Independent Learner", "Anywhere"),
]

SEMESTERS = [
    (1, "Semester 1", 1),
    (2, "Semester 2", 1),
    (3, "Semester 3", 2),
    (4, "Semester 4", 2),
    (5, "Semester 5", 3),
    (6, "Semester 6", 3),
    (7, "Semester 7", 4),
    (8, "Semester 8", 4),
    (0, "Any / Foundation", None),
]

# (slug, name, branch, sem, first_year, code, credits, difficulty, icon, color, description)
SUBJECTS = [
    # ---------------- FIRST YEAR COMMON (spec §4) ----------------
    ("engineering-mathematics-1", "Engineering Mathematics I", None, 1, True, "MA101", 4, "medium", "sigma", "#4f7cff",
     "Calculus, differential equations and linear algebra foundations every engineer uses."),
    ("engineering-mathematics-2", "Engineering Mathematics II", None, 2, True, "MA102", 4, "medium", "sigma", "#4f7cff",
     "Multivariable calculus, vector calculus, Laplace transforms and probability."),
    ("engineering-mathematics-3", "Engineering Mathematics III", None, 3, True, "MA201", 4, "hard", "sigma", "#4f7cff",
     "Complex variables, partial differential equations, numerical methods and statistics."),
    ("engineering-physics", "Engineering Physics", None, 1, True, "PH101", 4, "medium", "atom", "#8b5cf6",
     "Waves, optics, quantum basics, semiconductors and materials for engineers."),
    ("engineering-chemistry", "Engineering Chemistry", None, 1, True, "CY101", 4, "medium", "flask-conical", "#ec4899",
     "Electrochemistry, polymers, fuels, corrosion and water treatment."),
    ("engineering-graphics", "Engineering Graphics", None, 1, True, "ME103", 3, "easy", "ruler", "#f59e0b",
     "Projections, orthographic views, sections and isometric drawing standards."),
    ("engineering-drawing", "Engineering Drawing & CAD", None, 2, True, "ME104", 3, "easy", "pen-tool", "#f59e0b",
     "Drafting standards plus modern CAD workflow and dimensioning."),
    ("basic-electrical", "Basic Electrical Engineering", None, 2, True, "EE101", 4, "medium", "zap", "#eab308",
     "DC/AC circuits, network theorems, transformers and machines."),
    ("basic-electronics", "Basic Electronics", None, 2, True, "EC101", 4, "medium", "circuit-board", "#f97316",
     "Diodes, BJTs, op-amps, digital logic and instrumentation basics."),
    ("programming-fundamentals", "Programming Fundamentals", None, 1, True, "CS101", 4, "easy", "terminal", "#22c55e",
     "Your first programming language: logic, control flow, functions and arrays."),
    ("engineering-mechanics-fy", "Engineering Mechanics", None, 2, True, "ME101", 4, "medium", "move", "#64748b",
     "Statics, force systems, friction, trusses and rigid body equilibrium."),
    ("communication-skills", "Communication Skills", None, 2, True, "HS101", 2, "easy", "message-square", "#06b6d4",
     "Technical writing, presentations and interview communication."),
    ("environmental-studies", "Environmental Studies", None, 2, True, "HS102", 2, "easy", "leaf", "#16a34a",
     "Ecosystems, pollution, sustainability and environmental law."),
    ("workshop-practice", "Workshop Practice", None, 1, True, "ME102", 2, "easy", "hammer", "#78716c",
     "Fitting, smithy, welding, carpentry and safety on the shop floor."),

    # ---------------- CSE / IT ----------------
    ("data-structures-algorithms", "Data Structures & Algorithms", "computer-science", 3, False, "CS201", 4, "hard", "git-fork", "#4f7cff",
     "The single highest-leverage subject in computing - and the core of every interview."),
    ("oops", "Object Oriented Programming", "computer-science", 3, False, "CS202", 4, "medium", "boxes", "#22c55e",
     "Classes, inheritance, polymorphism and how to model real systems."),
    ("dbms", "Database Management Systems", "computer-science", 4, False, "CS203", 4, "medium", "database", "#0ea5e9",
     "Relational modelling, SQL, normalisation, indexing and transactions."),
    ("operating-systems", "Operating Systems", "computer-science", 4, False, "CS204", 4, "hard", "hard-drive", "#6366f1",
     "Processes, scheduling, memory, file systems and concurrency."),
    ("computer-networks", "Computer Networks", "computer-science", 5, False, "CS301", 4, "hard", "network", "#06b6d4",
     "The layered model from physical signals to TCP and HTTP."),
    ("computer-architecture", "Computer Organization & Architecture", "computer-science", 3, False, "CS205", 4, "hard", "cpu", "#a855f7",
     "How a processor actually executes your code, and why caches matter."),
    ("theory-of-computation", "Theory of Computation", "computer-science", 5, False, "CS302", 4, "hard", "infinity", "#8b5cf6",
     "Automata, grammars, decidability and the limits of computation."),
    ("compiler-design", "Compiler Design", "computer-science", 6, False, "CS303", 4, "hard", "file-code", "#e11d48",
     "Lexing, parsing, semantic analysis and code generation."),
    ("software-engineering", "Software Engineering", "software-engineering", 5, False, "CS304", 3, "medium", "clipboard-check", "#14b8a6",
     "Process models, requirements, design, testing and quality."),
    ("machine-learning", "Machine Learning", "ai-ml", 6, False, "AI301", 4, "hard", "brain-circuit", "#8b5cf6",
     "Supervised, unsupervised and reinforcement learning with real maths."),
    ("deep-learning", "Deep Learning", "ai-ml", 7, False, "AI401", 4, "hard", "network", "#a855f7",
     "Neural networks, CNNs, transformers and training at scale."),
    ("data-science-foundations", "Data Science Foundations", "data-science", 5, False, "DS301", 4, "medium", "bar-chart-3", "#06b6d4",
     "Statistics, data wrangling and visualisation for engineers."),
    ("cryptography-security", "Cryptography & Network Security", "cyber-security", 6, False, "SE301", 4, "hard", "shield", "#ef4444",
     "Symmetric and public key crypto, hashes, TLS and attack models."),
    ("cloud-computing-subject", "Cloud Computing", "cloud-computing", 7, False, "CC401", 3, "medium", "cloud", "#0ea5e9",
     "Virtualisation, elasticity, distributed storage and serverless."),
    ("web-technologies", "Web Technologies", "information-technology", 4, False, "IT201", 3, "easy", "globe", "#f97316",
     "HTML, CSS, JavaScript, HTTP and modern full-stack patterns."),
    ("discrete-mathematics", "Discrete Mathematics", "computer-science", 3, False, "MA203", 4, "hard", "sigma", "#4f7cff",
     "Logic, sets, relations, graph theory and combinatorics."),
    ("digital-logic-design", "Digital Logic Design", "computer-science", 3, False, "CS206", 3, "medium", "binary", "#64748b",
     "Boolean algebra, combinational and sequential circuits."),

    # ---------------- MECHANICAL ----------------
    ("thermodynamics", "Engineering Thermodynamics", "mechanical-engineering", 3, False, "ME201", 4, "hard", "flame", "#ef4444",
     "Energy, entropy and the laws that govern every engine and power plant."),
    ("fluid-mechanics", "Fluid Mechanics", "mechanical-engineering", 4, False, "ME202", 4, "hard", "waves", "#0ea5e9",
     "Statics, kinematics and dynamics of fluids - Bernoulli to boundary layers."),
    ("strength-of-materials", "Strength of Materials", "mechanical-engineering", 4, False, "ME203", 4, "hard", "columns", "#f59e0b",
     "Stress, strain, bending, torsion and how things fail."),
    ("manufacturing-processes", "Manufacturing Processes", "manufacturing", 4, False, "ME204", 4, "medium", "factory", "#475569",
     "Casting, forming, machining, joining and additive manufacturing."),
    ("machine-design", "Machine Design", "mechanical-engineering", 6, False, "ME301", 4, "hard", "settings", "#64748b",
     "Designing shafts, gears, springs, bearings and welded joints for real loads."),
    ("heat-transfer", "Heat & Mass Transfer", "mechanical-engineering", 5, False, "ME302", 4, "hard", "thermometer", "#dc2626",
     "Conduction, convection, radiation and heat exchanger design."),
    ("theory-of-machines", "Theory of Machines", "mechanical-engineering", 5, False, "ME303", 4, "hard", "cog", "#78716c",
     "Kinematics of mechanisms, gears, cams, governors and balancing."),
    ("ic-engines", "Internal Combustion Engines", "automobile", 6, False, "AU301", 4, "medium", "engine", "#b91c1c",
     "SI/CI cycles, fuel systems, emissions and engine performance."),
    ("cad-cam", "CAD / CAM", "mechanical-engineering", 6, False, "ME304", 3, "medium", "box", "#0891b2",
     "Parametric modelling, assembly design and CNC programming."),
    ("refrigeration-ac", "Refrigeration & Air Conditioning", "mechanical-engineering", 7, False, "ME401", 3, "medium", "snowflake", "#38bdf8",
     "Vapour compression cycles, psychrometrics and system design."),

    # ---------------- ECE ----------------
    ("electronic-devices", "Electronic Devices & Circuits", "electronics-communication", 3, False, "EC201", 4, "hard", "cpu", "#f97316",
     "Semiconductor physics, diodes, BJTs, FETs and amplifiers."),
    ("digital-electronics", "Digital Electronics", "electronics-communication", 3, False, "EC202", 4, "medium", "binary", "#eab308",
     "Boolean algebra, logic families, combinational and sequential design."),
    ("signals-systems", "Signals & Systems", "electronics-communication", 4, False, "EC203", 4, "hard", "activity", "#8b5cf6",
     "Convolution, Fourier, Laplace and Z transforms - the maths of signals."),
    ("communication-systems", "Communication Systems", "electronics-communication", 5, False, "EC301", 4, "hard", "radio-tower", "#06b6d4",
     "AM/FM, digital modulation, noise, sampling and information theory."),
    ("microprocessors", "Microprocessors & Microcontrollers", "embedded-systems", 5, False, "EC302", 4, "medium", "microchip", "#f43f5e",
     "8085/8086, ARM, assembly, interrupts and peripheral interfacing."),
    ("electromagnetic-fields", "Electromagnetic Fields", "electronics-communication", 4, False, "EC204", 4, "hard", "magnet", "#7c3aed",
     "Maxwell's equations, waves, transmission lines and radiation."),
    ("analog-circuits", "Analog Circuits", "electronics-engineering", 4, False, "EC205", 4, "hard", "audio-lines", "#f59e0b",
     "Amplifiers, feedback, oscillators and op-amp applications."),
    ("control-systems-subject", "Control Systems Engineering", "control-systems", 5, False, "EC303", 4, "hard", "sliders-horizontal", "#0d9488",
     "Transfer functions, stability, root locus, Bode and state space."),
    ("dsp", "Digital Signal Processing", "electronics-communication", 6, False, "EC304", 4, "hard", "waves", "#6366f1",
     "DFT/FFT, filter design and multirate processing."),
    ("vlsi-design-subject", "VLSI Design", "vlsi", 6, False, "EC305", 4, "hard", "cpu", "#e11d48",
     "CMOS logic, layout, timing analysis and the digital design flow."),

    # ---------------- EEE ----------------
    ("circuit-theory", "Circuit Theory", "electrical-engineering", 3, False, "EE201", 4, "hard", "zap", "#eab308",
     "Network analysis, theorems, transients and two-port networks."),
    ("electrical-machines-1", "Electrical Machines I", "electrical-engineering", 4, False, "EE202", 4, "hard", "rotate-cw", "#f59e0b",
     "Transformers and DC machines: construction, characteristics, testing."),
    ("electrical-machines-2", "Electrical Machines II", "electrical-engineering", 5, False, "EE301", 4, "hard", "rotate-3d", "#fb923c",
     "Induction and synchronous machines, torque and performance."),
    ("power-systems", "Power Systems", "electrical-engineering", 6, False, "EE302", 4, "hard", "tower-control", "#dc2626",
     "Generation, transmission lines, load flow, faults and protection."),
    ("power-electronics", "Power Electronics", "electrical-engineering", 6, False, "EE303", 4, "hard", "circuit-board", "#ef4444",
     "Rectifiers, choppers, inverters and converter control."),
    ("measurements-instrumentation", "Measurements & Instrumentation", "instrumentation", 4, False, "IN201", 3, "medium", "gauge", "#84cc16",
     "Bridges, transducers, CROs and measurement error analysis."),

    # ---------------- CIVIL ----------------
    ("surveying", "Surveying", "civil-engineering", 3, False, "CE201", 4, "medium", "compass", "#a16207",
     "Chain, compass, levelling, theodolite and modern total stations."),
    ("structural-analysis", "Structural Analysis", "structural", 5, False, "CE301", 4, "hard", "landmark", "#b45309",
     "Determinacy, moment distribution, slope-deflection and influence lines."),
    ("concrete-technology", "Concrete Technology", "civil-engineering", 4, False, "CE202", 4, "medium", "layers", "#78716c",
     "Cement chemistry, mix design, workability, strength and durability."),
    ("soil-mechanics", "Soil Mechanics / Geotechnical Engineering", "geotechnical", 5, False, "CE302", 4, "hard", "layers", "#92400e",
     "Index properties, permeability, consolidation, shear strength and bearing capacity."),
    ("rc-design", "Design of Reinforced Concrete Structures", "structural", 6, False, "CE303", 4, "hard", "building-2", "#a16207",
     "Limit state design of beams, slabs, columns and footings."),
    ("hydraulics", "Hydraulics & Hydraulic Machinery", "civil-engineering", 4, False, "CE203", 4, "hard", "droplets", "#0369a1",
     "Open channel flow, pipes, pumps and turbines."),
    ("transportation-engineering-subject", "Transportation Engineering", "transportation", 6, False, "CE304", 3, "medium", "route", "#ca8a04",
     "Highway alignment, pavement design and traffic engineering."),
    ("environmental-engineering-subject", "Environmental Engineering", "environmental", 6, False, "CE305", 3, "medium", "leaf", "#16a34a",
     "Water supply, wastewater treatment and solid waste management."),
    ("estimating-costing", "Estimating & Costing", "construction", 7, False, "CE401", 3, "easy", "calculator", "#d97706",
     "Quantity take-off, rate analysis, tendering and contracts."),

    # ---------------- CHEMICAL ----------------
    ("process-calculations", "Process Calculations", "chemical-engineering", 3, False, "CH201", 4, "medium", "calculator", "#db2777",
     "Material and energy balances - the accountant's skill of chemical engineering."),
    ("chemical-thermodynamics", "Chemical Engineering Thermodynamics", "chemical-engineering", 4, False, "CH202", 4, "hard", "flame", "#e11d48",
     "PVT behaviour, property relations, fugacity and equilibrium."),
    ("fluid-flow-operations", "Fluid Flow Operations", "chemical-engineering", 4, False, "CH203", 4, "hard", "waves", "#0ea5e9",
     "Flow through pipes, pumps, fluidisation and dimensional analysis."),
    ("heat-transfer-operations", "Heat Transfer Operations", "chemical-engineering", 5, False, "CH301", 4, "hard", "thermometer", "#f97316",
     "Exchanger design, evaporation, condensation and boiling."),
    ("mass-transfer", "Mass Transfer Operations", "chemical-engineering", 6, False, "CH302", 4, "hard", "shuffle", "#9333ea",
     "Diffusion, absorption, distillation, extraction and drying."),
    ("reaction-engineering", "Chemical Reaction Engineering", "chemical-engineering", 6, False, "CH303", 4, "hard", "flask-conical", "#c026d3",
     "Kinetics, reactor design, residence time and non-ideal flow."),
    ("materials-science", "Materials Science & Engineering", "materials", 3, False, "MM201", 4, "medium", "gem", "#7c3aed",
     "Crystal structure, defects, phase diagrams, mechanical behaviour and failure."),
]
